services:
  steamcmd:
    container_name: palworld
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8211:8211/udp"
    volumes:
      - /home/palworld/save:/home/steam/.steam/steam/steamapps/common/PalServer/Pal/Saved/SaveGames/0/
    restart: unless-stopped