services:
  steamcmd:
    container_name: palworld
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8211:8211/udp"
    restart: unless-stopped
    volumes:
      - /home/palworld:/home/steam/Pal