services:
  steamcmd:
    container_name: palworld
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8211:8211/udp"
      - "8212:8212/tcp"
      - "25575:25575/tcp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8212/v1/api/info"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s